# Generated by Django 2.1.4 on 2019-03-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('sex', models.CharField(max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('datatime', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
