"""
Django settings for DjangoCaptcha project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'll_n^9@7*enxjf1qa4gh@&aiky6&iai8+df2p0pq)ysw(89$^0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'captcha'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoCaptcha.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoCaptcha.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_captcha',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '10.0.90.190',
        'PORT': '3306',
        "OPTIONS": {"init_command": "SET default_storage_engine=INNODB;"}
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'



# 图像验证码格式，可以自定义。
CAPTCHA_OUTPUT_FORMAT = u'%(text_field)s  %(image)s %(hidden_field)s'
# 添加干扰点、干扰线
CAPTCHA_NOISE_FUNCTIONS = (
    'captcha.helpers.noise_null',
    'captcha.helpers.noise_arcs',  # 干扰线
    'captcha.helpers.noise_dots',  # 干扰点
)
# 图片大小
CAPTCHA_IMAGE_SIZE = (100, 25)
# 背景颜色
CAPTCHA_BACKGROUND_COLOR = '#ffffff'
# 验证码的样式
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'  # 随机字符
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'    # 数学表达式
# 字符个数
CAPTCHA_LENGTH = 4
# 超时时间（分钟）
CAPTCHA_TIMEOUT = 1


# 缓存配置
CACHES = {
     "default": {
	 "BACKEND": "django_redis.cache.RedisCache",
	 "LOCATION": "redis://127.0.0.1:6379/9",
	 "OPTIONS": {
	    "CLIENT_CLASS": "django_redis.client.DefaultClient",
	}
	 },
	 # django session存 reidis 1 号库（现在基本不需要使⽤）
	 "session": {
	 "BACKEND": "django_redis.cache.RedisCache",
	 "LOCATION": "redis://127.0.0.1:6379/10",
	 "OPTIONS": {
	 "CLIENT_CLASS": "django_redis.client.DefaultClient",
	 }
	 },
     # 图形验证码，存redis 2号库
     "img_code": {
         "BACKEND": "django_redis.cache.RedisCache",
         "LOCATION": "redis://127.0.0.1:6379/11",
         "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
     }
}
# 配置session使⽤redis存储
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# 配置session存储的位置: 使⽤cache中的
SESSION_CACHE_ALIAS = "session"
